### ISSUE TITLE
Add plugins support

### ISSUE THREAD

**Issue by sayanarijit** [sayanarijit/RESTEasyCLI#18]
Plugins can be added as custom classes having an `apply()` method, kept in `plugins` directory inside any of *Config.SEARCH_PATHS*.
Plugin's `__init__()` will take *workspace* instance as input. `apply` will take `resteasy.APIEndpoint` instance and do whatever it wants with it.
Plugins can be applied by `sites.yml` or `saved.yml` files as shown:

**sites.yml**
```yaml
  testing:
    base_url: https://jsonplaceholder.typicode.com
    plugins:
      - someorg.somerepo.formatter:MyCustomDecoder
    endpoints:
      todos:
        route: todos
        plugins:
          - someorg.somerepo.formatter:MyCustomEncoder
      todo1:
        route: todos/1
```

**plugins/someorg/somerepo/formatter.py**
```python
class MyCustomDecoder(object):
    def __init__(self, workspace):
        self.workspace = workspace
        self.logger = workspace.logger
    def apply(self, api):
        api.decoder = yaml.load
```

As you might have guessed, there is scope of applying multiple plugins in specified order. Priority will be: saved (highest) > endpoint > site (lowest) i.e. same as what is applied to other properties.

Reusable plugins can be downloaded with an inbuilt plugin manager just like `go get` installs public packages in golang.

Plugins can be of different types to handle different tasks. Above is an example of a plugin that gets invoked when a request is made. Similarly we can have a type of plugin that gets invoked when a specific command is entered.

**Ideas for native plugins and alternate strategies are also welcome.**
